version: "3"

networks:
  nest-auth:

services:
  db:
    image:  postgres
    restart: always
    container_name: db
    ports:
      - ${DB_PORT}:${DB_PORT_CONTAINER}
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - "./databases:/var/lib/postgresql/data/"
    networks:
      - nest-auth
  app:
    build: .
    container_name: app
    ports:
      - ${WEB_PORT_HOST}:${WEB_PORT_CONTAINER}
    depends_on:
      - db
    volumes:
      - "./src:/usr/src/app/src"
    restart: unless-stopped
    environment:
      - NEST_DEBUG=true
    networks:
      - nest-auth
  redis:
    image: redis
    container_name: ${REDIS_CONTAINER_NAME}
    ports:
      - ${REDIS_PORT_HOST}:${REDIS_PORT_CONTAINER}
    volumes:
      - "./redis_data:/data"
    restart: always
    networks:
      - nest-auth
